### ISSUE TITLE
Don't assume that jdbcTimeField will be provided

### ISSUE THREAD

**Issue by ghost** [IBM-ITOAdev/logstash-input-genjdbc#1]
I am using this plugin to get a simple count of the total rows in a table at 10 minute intervals so I don't need to use the jdbcTimeField and I didn't provide it...

When I tested my setup, I had to change the plugin code to not expect it - the change I made is below - which is certainly not a good fix for general use but serves my purposes:

```
# if not, we'll implicity assemble query
  # Suggest removing this option completely and making it explicity
  # Escape sql query provided from config file
#    begin
#      if originalQuery.include? " where " then
#        escapedQuery = originalQuery + " and "+@jdbcTimeField+" > '" + jdbclastEvent + "'" + " order by " +@jdbcTimeField
#      else
#        escapedQuery = originalQuery + " where "+@jdbcTimeField+" > '" + jdbclastEvent + "'" +  " order by " +@jdbcTimeField
#      end
#    end
    escapedQuery = originalQuery
```

**Comment by stuarttuck** [comment]
Thanks for the Input, Actually this was originally coded without time fields and was able just to pull rows. However I added this in for a specific reason as a lot of collection as a service in logstash would be usually pulling data rows. But.. agree with you, It should be optional, especially for getting single rows of data to detect a change in state, for hierarchy type data, or just to pull meta data about tables periodically.

**Comment by ghost** [comment]
Great.   If you would like me to test after you make the code changes, please let me know.

Thanks,
Janice

Janice Gluck

[cid:image001.png@01CF858C.32055680]http://www1.good.com/[http://media.www1.good.com/images/icon-em-sig-facebook.png]https://www.facebook.com/goodformobile[http://media.www1.good.com/images/icon-em-sig-twitter.png]https://twitter.com/GOOD_technology[http://media.www1.good.com/images/icon-em-sig-linkedin.png]https://www.linkedin.com/company/good-technology[http://media.www1.good.com/images/icon-em-sig-youtube.png]https://www.youtube.com/user/GoodForMobile

**Comment by mtds** [comment]
I was able to launch my 'SELECT' query only after adding a 'workaround' to the code section Janice mentioned, without entirely comment it out:

```
158,162c158
<             if jdbcTimeField.nil?
<               escapedQuery = originalQuery
<             else
<               escapedQuery = originalQuery + " where "+@jdbcTimeField+" > '" + jdbclastEvent + "'" +  " order by " +@jdbcTimeField
<             end
---
>             escapedQuery = originalQuery + " where "+@jdbcTimeField+" > '" + jdbclastEvent + "'" +  " order by " +@jdbcTimeField
165a162
```

In this way my query is able to run and I got the results (I am using LS 1.5.1 and OpenJDK 7 with a MySQL connector) **but** at the same time I got also the following Java exceptions (and unfortunately I am still banging my head on why this is happening):

```
** BEGIN NESTED EXCEPTION **

java.lang.Throwable

STACKTRACE:

java.lang.Throwable
        at com.mysql.jdbc.log.LogUtils.expandProfilerEventIfNecessary(LogUtils.java:49)
        at com.mysql.jdbc.log.StandardLogger.logInternal(StandardLogger.java:293)
        at com.mysql.jdbc.log.StandardLogger.logInfo(StandardLogger.java:196)
        at com.mysql.jdbc.profiler.LoggingProfilerEventHandler.consumeEvent(LoggingProfilerEventHandler.java:46)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2905)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2820)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2769)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1569)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:456)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:317)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
        at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
        at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
        at org.jruby.runtime.Block.call(Block.java:101)
        at org.jruby.RubyProc.call(RubyProc.java:290)
        at org.jruby.RubyProc.call(RubyProc.java:228)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
        at java.lang.Thread.run(Thread.java:745)

** END NESTED EXCEPTION **
```
